spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_database?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#    数据库用户名
    username: root
#    数据库密码
    password:
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  servlet:
    multipart:
      max-file-size: 100MB
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080

logging:
  level:
    com.jdk.projectinterface.mapper.*: debug